[package]
name = "monero-rust-dependencies"
version = "0.0.0"
edition = "2021"

[lib]
name = "monerorust"
crate-type = [ "cdylib" ]

[dependencies]
pasta_curves = "0.5.0"

[build-dependencies]
cbindgen = "0.24.3"
